extends:
  - 'airbnb-base'
  - plugin:jsdoc/recommended
  - plugin:security/recommended
  - plugin:prettier/recommended

plugins:
  - jsdoc
  - security

rules:
  arrow-body-style: 0
  camelcase: 0
  consistent-return: 0
  func-names: 0
  function-paren-newline: 0
  global-require: 0
  no-multi-assign: 0
  no-param-reassign: 0
  no-underscore-dangle: 0
  prefer-arrow-callback: 0
  no-use-before-define: 0
  class-methods-use-this: 0

settings:
  jsdoc:
    preferredTypes:
      object: Object
      express: Express
      Function: function
      knex: Knex
    tagNamePreference:
      constant: const
      file: fileoverview
      returns: return
