extends: 'airbnb-base'

rules:
  arrow-body-style: 0
  camelcase: 0
  consistent-return: 0
  func-names: 0
  function-paren-newline: 0
  global-require: 0
  no-multi-assign: 0
  no-param-reassign: 0
  no-underscore-dangle: 0
  prefer-arrow-callback: 0
  no-use-before-define: 0
  class-methods-use-this: 0

globals:
  # Testing
  suite: true
  test: true
  describe: true
  it: true
  setup: true
  before: true
  beforeEach: true
  after: true
  afterEach: true
  teardown: true
  assert: true
  fit: true
  fdescribe: true
  expect: true
